# Generated by Django 3.2.8 on 2021-10-29 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('started_date', models.DateTimeField(verbose_name='date published')),
                ('finished_date', models.DateTimeField(verbose_name='date published')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.servicetype')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.servicestatus')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceItemServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('+', 'POSITIVE'), ('-', 'NEGATIVE')], max_length=2)),
                ('value', models.FloatField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.balanceitem')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.service')),
            ],
        ),
    ]
