# Generated by Django 3.2.8 on 2021-12-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20211219_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='finished_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='started_date',
            field=models.DateField(null=True),
        ),
    ]
