# Generated by Django 3.2.11 on 2022-01-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20211219_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceitemserviceentry',
            name='note',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
    ]
